// ########## Auto-Generated Code ##########
// <auto-generated>
// This code was automatically generated by a tool.
//
// Changes to this file may cause incorrect behaviour, and the changes will be lost if
// the code is regenerated.
// </auto-generated>
// ##########################################

using System;
using System.CodeDom.Compiler;
using GermanVocabApp.DataAccess.EntityFramework.Models;
using GermanVocabApp.Shared.Data;

namespace GermanVocabApp.DataAccess.EntityFramework.Tests.Unit.Builders;


[GeneratedCode("Builders", "1.0")]
public partial class VocabListBuilder : BuilderBase<GermanVocabApp.DataAccess.EntityFramework.Models.VocabList>
{
    private DateTime _createdDate;
    public VocabListBuilder WithCreatedDate(DateTime value)
    {
        _createdDate = value;
        return this;
    }
    private DateTime? _deletedDate;
    public VocabListBuilder WithDeletedDate(DateTime? value)
    {
        _deletedDate = value;
        return this;
    }
    private String _description;
    public VocabListBuilder WithDescription(String value)
    {
        _description = value;
        return this;
    }
    private Guid _id;
    public VocabListBuilder WithId(Guid value)
    {
        _id = value;
        return this;
    }
    //ListItems;
    private IEnumerable1 _listItems;
    public VocabListBuilder WithListItems(IEnumerable1 value)
    {
        _listItems = value;
        return this;
    }
    private String _name;
    public VocabListBuilder WithName(String value)
    {
        _name = value;
        return this;
    }
    private DateTime? _updatedDate;
    public VocabListBuilder WithUpdatedDate(DateTime? value)
    {
        _updatedDate = value;
        return this;
    }
    public override VocabList Build()
    {
        return new VocabList
        {
            CreatedDate = _createdDate,
            DeletedDate = _deletedDate,
            Description = _description,
            Id = _id,
            ListItems = _listItems,
            Name = _name,
            UpdatedDate = _updatedDate,

        };
    }
}

[GeneratedCode("Builders", "1.0")]
public partial class VocabListItemBuilder : BuilderBase<GermanVocabApp.DataAccess.EntityFramework.Models.VocabListItem>
{
    private AuxiliaryVerb? _auxiliaryVerb;
    public VocabListItemBuilder WithAuxiliaryVerb(AuxiliaryVerb? value)
    {
        _auxiliaryVerb = value;
        return this;
    }
    private String _comparative;
    public VocabListItemBuilder WithComparative(String value)
    {
        _comparative = value;
        return this;
    }
    private DateTime _createdDate;
    public VocabListItemBuilder WithCreatedDate(DateTime value)
    {
        _createdDate = value;
        return this;
    }
    private DateTime? _deletedDate;
    public VocabListItemBuilder WithDeletedDate(DateTime? value)
    {
        _deletedDate = value;
        return this;
    }
    private String _english;
    public VocabListItemBuilder WithEnglish(String value)
    {
        _english = value;
        return this;
    }
    private FixedPlurality? _fixedPlurality;
    public VocabListItemBuilder WithFixedPlurality(FixedPlurality? value)
    {
        _fixedPlurality = value;
        return this;
    }
    private Gender? _gender;
    public VocabListItemBuilder WithGender(Gender? value)
    {
        _gender = value;
        return this;
    }
    private String _german;
    public VocabListItemBuilder WithGerman(String value)
    {
        _german = value;
        return this;
    }
    private Guid _id;
    public VocabListItemBuilder WithId(Guid value)
    {
        _id = value;
        return this;
    }
    private Boolean? _isWeakMasculineNoun;
    public VocabListItemBuilder WithIsWeakMasculineNoun(Boolean? value)
    {
        _isWeakMasculineNoun = value;
        return this;
    }
    private String _perfect;
    public VocabListItemBuilder WithPerfect(String value)
    {
        _perfect = value;
        return this;
    }
    private String _plural;
    public VocabListItemBuilder WithPlural(String value)
    {
        _plural = value;
        return this;
    }
    private String _preposition;
    public VocabListItemBuilder WithPreposition(String value)
    {
        _preposition = value;
        return this;
    }
    private Case? _prepositionCase;
    public VocabListItemBuilder WithPrepositionCase(Case? value)
    {
        _prepositionCase = value;
        return this;
    }
    private ReflexiveCase? _reflexiveCase;
    public VocabListItemBuilder WithReflexiveCase(ReflexiveCase? value)
    {
        _reflexiveCase = value;
        return this;
    }
    private Separability? _separability;
    public VocabListItemBuilder WithSeparability(Separability? value)
    {
        _separability = value;
        return this;
    }
    private String _superlative;
    public VocabListItemBuilder WithSuperlative(String value)
    {
        _superlative = value;
        return this;
    }
    private String _thirdPersonImperfect;
    public VocabListItemBuilder WithThirdPersonImperfect(String value)
    {
        _thirdPersonImperfect = value;
        return this;
    }
    private String _thirdPersonPresent;
    public VocabListItemBuilder WithThirdPersonPresent(String value)
    {
        _thirdPersonPresent = value;
        return this;
    }
    private Transitivity? _transitivity;
    public VocabListItemBuilder WithTransitivity(Transitivity? value)
    {
        _transitivity = value;
        return this;
    }
    private DateTime? _updatedDate;
    public VocabListItemBuilder WithUpdatedDate(DateTime? value)
    {
        _updatedDate = value;
        return this;
    }
    private VocabList _vocabList;
    public VocabListItemBuilder WithVocabList(VocabList value)
    {
        _vocabList = value;
        return this;
    }
    private Guid _vocabListId;
    public VocabListItemBuilder WithVocabListId(Guid value)
    {
        _vocabListId = value;
        return this;
    }
    private WordType _wordType;
    public VocabListItemBuilder WithWordType(WordType value)
    {
        _wordType = value;
        return this;
    }
    public override VocabListItem Build()
    {
        return new VocabListItem
        {
            AuxiliaryVerb = _auxiliaryVerb,
            Comparative = _comparative,
            CreatedDate = _createdDate,
            DeletedDate = _deletedDate,
            English = _english,
            FixedPlurality = _fixedPlurality,
            Gender = _gender,
            German = _german,
            Id = _id,
            IsWeakMasculineNoun = _isWeakMasculineNoun,
            Perfect = _perfect,
            Plural = _plural,
            Preposition = _preposition,
            PrepositionCase = _prepositionCase,
            ReflexiveCase = _reflexiveCase,
            Separability = _separability,
            Superlative = _superlative,
            ThirdPersonImperfect = _thirdPersonImperfect,
            ThirdPersonPresent = _thirdPersonPresent,
            Transitivity = _transitivity,
            UpdatedDate = _updatedDate,
            VocabList = _vocabList,
            VocabListId = _vocabListId,
            WordType = _wordType,

        };
    }
}
 


