// <auto-generated>
using System;
using System.Runtime;
using System.CodeDom.Compiler;
using GermanVocabApp.DataAccess.EntityFramework.Models;
using GermanVocabApp.Shared.Data;

namespace GermanVocabApp.Core.SourceGeneration.Builders;

/*
System.TypeLoadException: Could not load type 'AppendInterpolatedStringHandler' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at GermanVocabApp.Core.SourceGeneration.Builders.Generators.ModelBuilderMemberGenerator.Append(ModelBuilderPropertyInfo propertyInfo)
   at Submission#0.TestStuff()
*/

